BACKEND_URL = "https://jwt-verification-sk0m.onrender.com"

PI_ID = "pi1"
RPI_BRIDGE_HOST = "0.0.0.0"
RPI_BRIDGE_PORT = 8080
RPI_BRIDGE_ADVERTISED_URL = ""
HEARTBEAT_INTERVAL_SECONDS = 10

JWT_ALGORITHM = "RS256"
